
server:
  port: 8089

spring:
  application:
    name: provincial
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_docker?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    min-idle: 5
    max-idle: 100
    max-wait: 10000
    validation-query: SELECT 1
    test-on-borrow: true
    test-while-idle: true
    time-between-eviction-runs-millis: 60000

mybatis:
  mapperLocations: classpath*:mybatis/**/*Mapper.xml

logging:
  file: boot.log
  path: /
  level:
    root: info